import {User} from "../models/userModel.js";
import {generateToken} from "../config/jwtToken.js";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";

export const getUsers = async (req, res) => {
  try {
    const users = await User.find({role: "buyer"});
    res.status(200).json(users);
  } catch (err) {
    res.status(404).json({error: err.message});
  }
};

export const createUser = async (req, res) => {
  try {
    if (req.body.role !== "buyer") {
      res
        .status(403)
        .json({error: "You are not authorized to create this user!"});
    }

    const email = req.body.email;
    const findUser = await User.findOne({email});

    if (findUser) {
      res.status(400).json({message: "User already exists"});
    }

    const newUser = new User.create(req.body);
    await newUser.save();
    res.status(201).json(newUser);
  } catch (err) {
    res.status(400).json({error: err.message});
  }
};

export const deleteUserByID = async (req, res) => {
  try {
    if (req.params.role !== "buyer") {
      res
        .status(403)
        .json({error: "You are not authorized to delete this user!"});
    }

    const id = req.params.id;
    const delUser = await User.findOneAndDelete({id});

    if (!delUser) {
      res.status(404).json({error: "User doesn't exist!"});
      return;
    }
    res.status(204).json({message: "User successfully deleted"});
  } catch (err) {
    res.status(404).json({error: err.message});
  }
};

export const loginUser = async (req, res) => {
  try {
    if (res.body.role !== "buyer") {
      res.status(403).json({error: "You are not authorized to login!"});
    }

    const {email, password} = req.body;

    // check if user exists or not
    const findUser = await User.findOne({email});

    if (findUser) {
      const passwordMatch = await bcrypt.compare(password, findUser.password);

      if (!passwordMatch) {
        res.status(400).json({error: "Password doesn't match"});
      }

      const accessToken = await generateToken(findUser._id);
      // Refresh tokens are random strings generated by the authentication server.
      // They are generated after successful authentication
      const refreshToken = await generateToken(findUser._id);
      const updateUser = await User.findByIdAndUpdate(
        findUser?._id,
        {refreshToken: refreshToken},
        {new: true}
      );
      res.cookie("refreshToken", refreshToken, {
        httpOnly: true,
        maxAge: 72 * 60 * 60 * 1000,
      });

      // return token
      res.status(200).json({
        _id: findUser?._id,
        name: findUser?.name,
        email: findUser?.email,
        mobile: findUser?.mobile,
        token: accessToken,
      });
    } else {
      res.status(400).json({error: "Account doesn't exist"});
    }
  } catch (err) {
    res.status(400).json({error: err.message});
  }
};

export const getUserByName = async (req, res) => {
  // try {
  //   const name = req.params.name;
  //   const user = await User.find({name});
  //   if (user.length === 0) {
  //     return res.status(404).json({error: "User not found!"});
  //   }
  //   res.status(200).json(user);
  // } catch (err) {
  //   res.status(404).json({error: err.message});
  // }
};

export const logoutUser = async (req, res) => {
  try {
    // delete all cookie
    if (req.params.role !== "buyer") {
      res.status(403).json({error: "You are not authorized to logout!"});
    }

    const cookie = req.cookies;
    if (!cookie.refreshToken) {
      res.status(400).json({message: "No refresh token in cookie"});
    }

    const refreshToken = cookie.refreshToken;
    const user = await User.findOne({refreshToken: refreshToken});
    if (!user) {
      res.clearCookie("refreshToken", {
        httpOnly: true,
        secure: true,
      });
    } else {
      await User.findByIdAndUpdate(user._id, {refreshToken: null});
      res.clearCookie("refreshToken", {
        httpOnly: true,
        secure: true,
      });
    }

    res.status(200).json({message: "Logout successfully!"});
  } catch (err) {
    res.status(400).json({error: err.message});
  }
};

export const deleteUser = async (req, res) => {
  try {
    const id = req.params.id;
    const user = await User.findByIdAndDelete(id);

    if (!user) {
      res.status(200).json({message: "Delete user successfully!"}, user);
    }
  } catch (err) {
    res.status(400).json({error: err.message});
  }
};

export const blockUser = async (req, res) => {
  try {
    const id = req.params.id;
    const user = await User.findByIdAndUpdate(
      id,
      {isBlocked: true},
      {new: true}
    );

    if (!user) {
      res.status(200).json({message: "Block user successfully!"}, user);
    }
  } catch (err) {
    res.status(400).json({error: err.message});
  }
};

export const unblockUser = async (req, res) => {
  try {
    const id = req.params.id;
    const user = await User.findByIdAndUpdate(id, {isBlocked: false}, {new: true});

    if (!user) {
      res.status(200).json({message: "Unblock user successfully!", user});
    }
  } catch (err) {
    res.status(400).json({error: err.message});
  }
}
